package utils

// Copyright (c) 2026 LingByte. All rights reserved.
// SPDX-License-Identifier: AGPL-3.0

import (
	"encoding/base64"
	"errors"
	"fmt"
	"math/rand"
	"os"
	"reflect"
	"strconv"
	"sync"
	"time"

	"github.com/LingByte/LingVoice/pkg/logger"
	"go.uber.org/zap"
)

var SnowflakeUtil *Snowflake
var letterRunes = []rune("0123456789abcdefghijklmnopqrstuvwxyz")
var numberRunes = []rune("0123456789")

func init() {
	rand.Seed(time.Now().UnixNano())
	SnowflakeUtil, _ = NewSnowflake()
}

// GenUintID returns a non-zero uint id generated by Snowflake.
// Note: Snowflake.NextID() is positive int64; on 64-bit platforms uint can hold it.
func GenUintID() uint {
	if SnowflakeUtil == nil {
		SnowflakeUtil, _ = NewSnowflake()
	}
	id := SnowflakeUtil.NextID()
	if id <= 0 {
		// best-effort fallback (should not happen)
		id = time.Now().UnixNano()
		if id < 0 {
			id = -id
		}
	}
	return uint(id)
}

func randRunes(n int, source []rune) string {
	b := make([]rune, n)
	for i := range b {
		b[i] = source[rand.Intn(len(source))]
	}
	return string(b)
}

func RandText(n int) string {
	return randRunes(n, letterRunes)
}

func RandNumberText(n int) string {
	return randRunes(n, numberRunes)
}

func RandString(n int) string {
	return randRunes(n, letterRunes)
}

// RandCredentialAPIKey 生成用户凭证密钥，形如 sk- 前缀 + 随机段，总长 48（与 credential.key char(48) 一致）。
func RandCredentialAPIKey() string {
	const prefix = "sk-"
	const totalLen = 48
	return prefix + RandString(totalLen-len(prefix))
}

func GetTimestamp() int64 {
	return time.Now().Unix()
}

func GetTimeString() string {
	now := time.Now().UTC()
	return fmt.Sprintf("%s%d", now.Format("20060102150405"), now.UnixNano()%1e9)
}

func SafeCall(f func() error, failHandle func(error)) error {
	defer func() {
		if err := recover(); err != nil {
			if failHandle != nil {
				eo, ok := err.(error)
				if !ok {
					es, ok := err.(string)
					if ok {
						eo = errors.New(es)
					} else {
						eo = errors.New("unknown error type")
					}
				}
				failHandle(eo)
			} else {
				logger.Error("panic", zap.Any("error", err))
			}
		}
	}()
	return f()
}

func StructAsMap(form any, fields []string) (vals map[string]any) {
	vals = make(map[string]any)
	v := reflect.ValueOf(form)
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		return vals
	}
	for i := 0; i < len(fields); i++ {
		k := v.FieldByName(fields[i])
		if !k.IsValid() || k.IsZero() {
			continue
		}
		if k.Kind() == reflect.Ptr {
			if !k.IsNil() {
				vals[fields[i]] = k.Elem().Interface()
			}
		} else {
			vals[fields[i]] = k.Interface()
		}
	}
	return vals
}

// GenerateSecureToken generate a fixed-length secure token
func GenerateSecureToken(length int) (string, error) {
	token := make([]byte, length)
	if _, err := rand.Read(token); err != nil {
		return "", err
	}
	return base64.URLEncoding.EncodeToString(token), nil
}

const (
	machineIDBits = 10
	sequenceBits  = 12

	maxMachineID = 1<<machineIDBits - 1
	maxSequence  = 1<<sequenceBits - 1

	timestampShift = machineIDBits + sequenceBits
	machineIDShift = sequenceBits

	epoch int64 = 1609459200000 // 2021-01-01 毫秒级
)

type Snowflake struct {
	mu        sync.Mutex
	lastStamp int64
	sequence  int64
	machineID int64
}

func NewSnowflake() (*Snowflake, error) {
	mid := getMachineID()
	if mid < 0 || mid > maxMachineID {
		return nil, errors.New("machine id out of range")
	}
	return &Snowflake{
		machineID: mid,
		sequence:  0,
		lastStamp: time.Now().UnixMilli(),
	}, nil
}

// NextID 生成 唯一 正数 int64
func (sf *Snowflake) NextID() int64 {
	sf.mu.Lock()
	defer sf.mu.Unlock()

	now := time.Now().UnixMilli()

	if now < sf.lastStamp {
		for now < sf.lastStamp {
			now = time.Now().UnixMilli()
		}
	}

	if now == sf.lastStamp {
		sf.sequence = (sf.sequence + 1) & maxSequence
		if sf.sequence == 0 {
			for now <= sf.lastStamp {
				now = time.Now().UnixMilli()
			}
		}
	} else {
		sf.sequence = 0
	}

	sf.lastStamp = now

	// 标准格式：0 | 41位时间 | 10位机器 | 12位序列
	return ((now - epoch) << timestampShift) |
		(sf.machineID << machineIDShift) |
		sf.sequence
}

// GenID 字符串格式（正数）
func (sf *Snowflake) GenID() string {
	return strconv.FormatInt(sf.NextID(), 10)
}

func getMachineID() int64 {
	midStr := os.Getenv("MACHINE_ID")
	if midStr == "" {
		return 1
	}
	mid, err := strconv.ParseInt(midStr, 10, 64)
	if err != nil {
		return 1
	}
	return mid
}

// ComputeSampleByteCount calculates bytes per millisecond for given audio parameters
func ComputeSampleByteCount(rate, depth, chans int) int {
	// Optimized: rate * depth / 8 / 1000 * chans
	// Reordered for better precision: (rate * depth * chans) / 8000
	return (rate * depth * chans) / 8000
}

// ValidateAndNormalizeDuration uses different validation logic with explicit bounds checking
func NormalizeFramePeriod(d string) time.Duration {
	parsed, err := time.ParseDuration(d)
	if err != nil {
		return 20 * time.Millisecond
	}
	if parsed == 0 {
		return 20 * time.Millisecond
	}

	// Use explicit range checks instead of compound condition
	if parsed < 10*time.Millisecond {
		return 20 * time.Millisecond
	}
	if parsed > 300*time.Millisecond {
		return 20 * time.Millisecond
	}
	return parsed
}
