[package]
name = "lm-dsp"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
silero = ["dep:silero-vad-pure"]

[dependencies]
lm-core = { path = "../lm-core" }
audio-codec.workspace = true
anyhow.workspace = true
rustfft.workspace = true
silero-vad-pure = { version = "0.1.1", default-features = false, optional = true }
