[package]
name = "lm-recorder"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
lm-core = { path = "../lm-core" }
lm-depacketizer = { path = "../lm-depacketizer" }
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3"
