// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: media_node.proto

package mediav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaNode_HealthCheck_FullMethodName          = "/lingvoice.media.v1.MediaNode/HealthCheck"
	MediaNode_CreateSession_FullMethodName        = "/lingvoice.media.v1.MediaNode/CreateSession"
	MediaNode_DestroySession_FullMethodName       = "/lingvoice.media.v1.MediaNode/DestroySession"
	MediaNode_AddEndpoint_FullMethodName          = "/lingvoice.media.v1.MediaNode/AddEndpoint"
	MediaNode_RemoveEndpoint_FullMethodName       = "/lingvoice.media.v1.MediaNode/RemoveEndpoint"
	MediaNode_AddTrack_FullMethodName             = "/lingvoice.media.v1.MediaNode/AddTrack"
	MediaNode_RemoveTrack_FullMethodName          = "/lingvoice.media.v1.MediaNode/RemoveTrack"
	MediaNode_PushRtp_FullMethodName              = "/lingvoice.media.v1.MediaNode/PushRtp"
	MediaNode_PullRtp_FullMethodName              = "/lingvoice.media.v1.MediaNode/PullRtp"
	MediaNode_InjectAudio_FullMethodName          = "/lingvoice.media.v1.MediaNode/InjectAudio"
	MediaNode_StartRecording_FullMethodName       = "/lingvoice.media.v1.MediaNode/StartRecording"
	MediaNode_StopRecording_FullMethodName        = "/lingvoice.media.v1.MediaNode/StopRecording"
	MediaNode_StartMix_FullMethodName             = "/lingvoice.media.v1.MediaNode/StartMix"
	MediaNode_StopMix_FullMethodName              = "/lingvoice.media.v1.MediaNode/StopMix"
	MediaNode_AddMixParticipant_FullMethodName    = "/lingvoice.media.v1.MediaNode/AddMixParticipant"
	MediaNode_RemoveMixParticipant_FullMethodName = "/lingvoice.media.v1.MediaNode/RemoveMixParticipant"
	MediaNode_SetMixGain_FullMethodName           = "/lingvoice.media.v1.MediaNode/SetMixGain"
	MediaNode_BridgeSessions_FullMethodName       = "/lingvoice.media.v1.MediaNode/BridgeSessions"
	MediaNode_UnbridgeSessions_FullMethodName     = "/lingvoice.media.v1.MediaNode/UnbridgeSessions"
	MediaNode_SendDtmf_FullMethodName             = "/lingvoice.media.v1.MediaNode/SendDtmf"
	MediaNode_Events_FullMethodName               = "/lingvoice.media.v1.MediaNode/Events"
	MediaNode_GetStats_FullMethodName             = "/lingvoice.media.v1.MediaNode/GetStats"
)

// MediaNodeClient is the client API for MediaNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MediaNode 服务 — Go 控制面 → Rust 媒体面
type MediaNodeClient interface {
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// 会话管理
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error)
	// 端点管理
	AddEndpoint(ctx context.Context, in *AddEndpointRequest, opts ...grpc.CallOption) (*AddEndpointResponse, error)
	RemoveEndpoint(ctx context.Context, in *RemoveEndpointRequest, opts ...grpc.CallOption) (*RemoveEndpointResponse, error)
	// 轨道管理
	AddTrack(ctx context.Context, in *AddTrackRequest, opts ...grpc.CallOption) (*AddTrackResponse, error)
	RemoveTrack(ctx context.Context, in *RemoveTrackRequest, opts ...grpc.CallOption) (*RemoveTrackResponse, error)
	// 媒体传输（核心热路径）
	PushRtp(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushRtpRequest, PushRtpResponse], error)
	PullRtp(ctx context.Context, in *PullRtpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RtpPacket], error)
	InjectAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InjectAudioRequest, InjectAudioResponse], error)
	// 媒体控制
	StartRecording(ctx context.Context, in *StartRecordingRequest, opts ...grpc.CallOption) (*StartRecordingResponse, error)
	StopRecording(ctx context.Context, in *StopRecordingRequest, opts ...grpc.CallOption) (*StopRecordingResponse, error)
	// 混音
	StartMix(ctx context.Context, in *StartMixRequest, opts ...grpc.CallOption) (*StartMixResponse, error)
	StopMix(ctx context.Context, in *StopMixRequest, opts ...grpc.CallOption) (*StopMixResponse, error)
	AddMixParticipant(ctx context.Context, in *AddMixParticipantRequest, opts ...grpc.CallOption) (*AddMixParticipantResponse, error)
	RemoveMixParticipant(ctx context.Context, in *RemoveMixParticipantRequest, opts ...grpc.CallOption) (*RemoveMixParticipantResponse, error)
	SetMixGain(ctx context.Context, in *SetMixGainRequest, opts ...grpc.CallOption) (*SetMixGainResponse, error)
	// 桥接
	BridgeSessions(ctx context.Context, in *BridgeSessionsRequest, opts ...grpc.CallOption) (*BridgeSessionsResponse, error)
	UnbridgeSessions(ctx context.Context, in *UnbridgeSessionsRequest, opts ...grpc.CallOption) (*UnbridgeSessionsResponse, error)
	// DTMF
	SendDtmf(ctx context.Context, in *SendDtmfRequest, opts ...grpc.CallOption) (*SendDtmfResponse, error)
	// 事件流
	Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MediaEvent], error)
	// 统计
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type mediaNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaNodeClient(cc grpc.ClientConnInterface) MediaNodeClient {
	return &mediaNodeClient{cc}
}

func (c *mediaNodeClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, MediaNode_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, MediaNode_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroySessionResponse)
	err := c.cc.Invoke(ctx, MediaNode_DestroySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) AddEndpoint(ctx context.Context, in *AddEndpointRequest, opts ...grpc.CallOption) (*AddEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddEndpointResponse)
	err := c.cc.Invoke(ctx, MediaNode_AddEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) RemoveEndpoint(ctx context.Context, in *RemoveEndpointRequest, opts ...grpc.CallOption) (*RemoveEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveEndpointResponse)
	err := c.cc.Invoke(ctx, MediaNode_RemoveEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) AddTrack(ctx context.Context, in *AddTrackRequest, opts ...grpc.CallOption) (*AddTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTrackResponse)
	err := c.cc.Invoke(ctx, MediaNode_AddTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) RemoveTrack(ctx context.Context, in *RemoveTrackRequest, opts ...grpc.CallOption) (*RemoveTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTrackResponse)
	err := c.cc.Invoke(ctx, MediaNode_RemoveTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) PushRtp(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushRtpRequest, PushRtpResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaNode_ServiceDesc.Streams[0], MediaNode_PushRtp_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PushRtpRequest, PushRtpResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaNode_PushRtpClient = grpc.ClientStreamingClient[PushRtpRequest, PushRtpResponse]

func (c *mediaNodeClient) PullRtp(ctx context.Context, in *PullRtpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RtpPacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaNode_ServiceDesc.Streams[1], MediaNode_PullRtp_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullRtpRequest, RtpPacket]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaNode_PullRtpClient = grpc.ServerStreamingClient[RtpPacket]

func (c *mediaNodeClient) InjectAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InjectAudioRequest, InjectAudioResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaNode_ServiceDesc.Streams[2], MediaNode_InjectAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InjectAudioRequest, InjectAudioResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaNode_InjectAudioClient = grpc.ClientStreamingClient[InjectAudioRequest, InjectAudioResponse]

func (c *mediaNodeClient) StartRecording(ctx context.Context, in *StartRecordingRequest, opts ...grpc.CallOption) (*StartRecordingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRecordingResponse)
	err := c.cc.Invoke(ctx, MediaNode_StartRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) StopRecording(ctx context.Context, in *StopRecordingRequest, opts ...grpc.CallOption) (*StopRecordingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRecordingResponse)
	err := c.cc.Invoke(ctx, MediaNode_StopRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) StartMix(ctx context.Context, in *StartMixRequest, opts ...grpc.CallOption) (*StartMixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartMixResponse)
	err := c.cc.Invoke(ctx, MediaNode_StartMix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) StopMix(ctx context.Context, in *StopMixRequest, opts ...grpc.CallOption) (*StopMixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopMixResponse)
	err := c.cc.Invoke(ctx, MediaNode_StopMix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) AddMixParticipant(ctx context.Context, in *AddMixParticipantRequest, opts ...grpc.CallOption) (*AddMixParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMixParticipantResponse)
	err := c.cc.Invoke(ctx, MediaNode_AddMixParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) RemoveMixParticipant(ctx context.Context, in *RemoveMixParticipantRequest, opts ...grpc.CallOption) (*RemoveMixParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMixParticipantResponse)
	err := c.cc.Invoke(ctx, MediaNode_RemoveMixParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) SetMixGain(ctx context.Context, in *SetMixGainRequest, opts ...grpc.CallOption) (*SetMixGainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMixGainResponse)
	err := c.cc.Invoke(ctx, MediaNode_SetMixGain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) BridgeSessions(ctx context.Context, in *BridgeSessionsRequest, opts ...grpc.CallOption) (*BridgeSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BridgeSessionsResponse)
	err := c.cc.Invoke(ctx, MediaNode_BridgeSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) UnbridgeSessions(ctx context.Context, in *UnbridgeSessionsRequest, opts ...grpc.CallOption) (*UnbridgeSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbridgeSessionsResponse)
	err := c.cc.Invoke(ctx, MediaNode_UnbridgeSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) SendDtmf(ctx context.Context, in *SendDtmfRequest, opts ...grpc.CallOption) (*SendDtmfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendDtmfResponse)
	err := c.cc.Invoke(ctx, MediaNode_SendDtmf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaNodeClient) Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MediaEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaNode_ServiceDesc.Streams[3], MediaNode_Events_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventsRequest, MediaEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaNode_EventsClient = grpc.ServerStreamingClient[MediaEvent]

func (c *mediaNodeClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, MediaNode_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaNodeServer is the server API for MediaNode service.
// All implementations must embed UnimplementedMediaNodeServer
// for forward compatibility.
//
// MediaNode 服务 — Go 控制面 → Rust 媒体面
type MediaNodeServer interface {
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// 会话管理
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error)
	// 端点管理
	AddEndpoint(context.Context, *AddEndpointRequest) (*AddEndpointResponse, error)
	RemoveEndpoint(context.Context, *RemoveEndpointRequest) (*RemoveEndpointResponse, error)
	// 轨道管理
	AddTrack(context.Context, *AddTrackRequest) (*AddTrackResponse, error)
	RemoveTrack(context.Context, *RemoveTrackRequest) (*RemoveTrackResponse, error)
	// 媒体传输（核心热路径）
	PushRtp(grpc.ClientStreamingServer[PushRtpRequest, PushRtpResponse]) error
	PullRtp(*PullRtpRequest, grpc.ServerStreamingServer[RtpPacket]) error
	InjectAudio(grpc.ClientStreamingServer[InjectAudioRequest, InjectAudioResponse]) error
	// 媒体控制
	StartRecording(context.Context, *StartRecordingRequest) (*StartRecordingResponse, error)
	StopRecording(context.Context, *StopRecordingRequest) (*StopRecordingResponse, error)
	// 混音
	StartMix(context.Context, *StartMixRequest) (*StartMixResponse, error)
	StopMix(context.Context, *StopMixRequest) (*StopMixResponse, error)
	AddMixParticipant(context.Context, *AddMixParticipantRequest) (*AddMixParticipantResponse, error)
	RemoveMixParticipant(context.Context, *RemoveMixParticipantRequest) (*RemoveMixParticipantResponse, error)
	SetMixGain(context.Context, *SetMixGainRequest) (*SetMixGainResponse, error)
	// 桥接
	BridgeSessions(context.Context, *BridgeSessionsRequest) (*BridgeSessionsResponse, error)
	UnbridgeSessions(context.Context, *UnbridgeSessionsRequest) (*UnbridgeSessionsResponse, error)
	// DTMF
	SendDtmf(context.Context, *SendDtmfRequest) (*SendDtmfResponse, error)
	// 事件流
	Events(*EventsRequest, grpc.ServerStreamingServer[MediaEvent]) error
	// 统计
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedMediaNodeServer()
}

// UnimplementedMediaNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaNodeServer struct{}

func (UnimplementedMediaNodeServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMediaNodeServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedMediaNodeServer) DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroySession not implemented")
}
func (UnimplementedMediaNodeServer) AddEndpoint(context.Context, *AddEndpointRequest) (*AddEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddEndpoint not implemented")
}
func (UnimplementedMediaNodeServer) RemoveEndpoint(context.Context, *RemoveEndpointRequest) (*RemoveEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveEndpoint not implemented")
}
func (UnimplementedMediaNodeServer) AddTrack(context.Context, *AddTrackRequest) (*AddTrackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTrack not implemented")
}
func (UnimplementedMediaNodeServer) RemoveTrack(context.Context, *RemoveTrackRequest) (*RemoveTrackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTrack not implemented")
}
func (UnimplementedMediaNodeServer) PushRtp(grpc.ClientStreamingServer[PushRtpRequest, PushRtpResponse]) error {
	return status.Error(codes.Unimplemented, "method PushRtp not implemented")
}
func (UnimplementedMediaNodeServer) PullRtp(*PullRtpRequest, grpc.ServerStreamingServer[RtpPacket]) error {
	return status.Error(codes.Unimplemented, "method PullRtp not implemented")
}
func (UnimplementedMediaNodeServer) InjectAudio(grpc.ClientStreamingServer[InjectAudioRequest, InjectAudioResponse]) error {
	return status.Error(codes.Unimplemented, "method InjectAudio not implemented")
}
func (UnimplementedMediaNodeServer) StartRecording(context.Context, *StartRecordingRequest) (*StartRecordingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRecording not implemented")
}
func (UnimplementedMediaNodeServer) StopRecording(context.Context, *StopRecordingRequest) (*StopRecordingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRecording not implemented")
}
func (UnimplementedMediaNodeServer) StartMix(context.Context, *StartMixRequest) (*StartMixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartMix not implemented")
}
func (UnimplementedMediaNodeServer) StopMix(context.Context, *StopMixRequest) (*StopMixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopMix not implemented")
}
func (UnimplementedMediaNodeServer) AddMixParticipant(context.Context, *AddMixParticipantRequest) (*AddMixParticipantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMixParticipant not implemented")
}
func (UnimplementedMediaNodeServer) RemoveMixParticipant(context.Context, *RemoveMixParticipantRequest) (*RemoveMixParticipantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMixParticipant not implemented")
}
func (UnimplementedMediaNodeServer) SetMixGain(context.Context, *SetMixGainRequest) (*SetMixGainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMixGain not implemented")
}
func (UnimplementedMediaNodeServer) BridgeSessions(context.Context, *BridgeSessionsRequest) (*BridgeSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BridgeSessions not implemented")
}
func (UnimplementedMediaNodeServer) UnbridgeSessions(context.Context, *UnbridgeSessionsRequest) (*UnbridgeSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbridgeSessions not implemented")
}
func (UnimplementedMediaNodeServer) SendDtmf(context.Context, *SendDtmfRequest) (*SendDtmfResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendDtmf not implemented")
}
func (UnimplementedMediaNodeServer) Events(*EventsRequest, grpc.ServerStreamingServer[MediaEvent]) error {
	return status.Error(codes.Unimplemented, "method Events not implemented")
}
func (UnimplementedMediaNodeServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedMediaNodeServer) mustEmbedUnimplementedMediaNodeServer() {}
func (UnimplementedMediaNodeServer) testEmbeddedByValue()                   {}

// UnsafeMediaNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaNodeServer will
// result in compilation errors.
type UnsafeMediaNodeServer interface {
	mustEmbedUnimplementedMediaNodeServer()
}

func RegisterMediaNodeServer(s grpc.ServiceRegistrar, srv MediaNodeServer) {
	// If the following call panics, it indicates UnimplementedMediaNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaNode_ServiceDesc, srv)
}

func _MediaNode_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_DestroySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).DestroySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_DestroySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).DestroySession(ctx, req.(*DestroySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_AddEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).AddEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_AddEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).AddEndpoint(ctx, req.(*AddEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_RemoveEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).RemoveEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_RemoveEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).RemoveEndpoint(ctx, req.(*RemoveEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_AddTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).AddTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_AddTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).AddTrack(ctx, req.(*AddTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_RemoveTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).RemoveTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_RemoveTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).RemoveTrack(ctx, req.(*RemoveTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_PushRtp_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MediaNodeServer).PushRtp(&grpc.GenericServerStream[PushRtpRequest, PushRtpResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaNode_PushRtpServer = grpc.ClientStreamingServer[PushRtpRequest, PushRtpResponse]

func _MediaNode_PullRtp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullRtpRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MediaNodeServer).PullRtp(m, &grpc.GenericServerStream[PullRtpRequest, RtpPacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaNode_PullRtpServer = grpc.ServerStreamingServer[RtpPacket]

func _MediaNode_InjectAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MediaNodeServer).InjectAudio(&grpc.GenericServerStream[InjectAudioRequest, InjectAudioResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaNode_InjectAudioServer = grpc.ClientStreamingServer[InjectAudioRequest, InjectAudioResponse]

func _MediaNode_StartRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).StartRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_StartRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).StartRecording(ctx, req.(*StartRecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_StopRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).StopRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_StopRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).StopRecording(ctx, req.(*StopRecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_StartMix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).StartMix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_StartMix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).StartMix(ctx, req.(*StartMixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_StopMix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopMixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).StopMix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_StopMix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).StopMix(ctx, req.(*StopMixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_AddMixParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMixParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).AddMixParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_AddMixParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).AddMixParticipant(ctx, req.(*AddMixParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_RemoveMixParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMixParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).RemoveMixParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_RemoveMixParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).RemoveMixParticipant(ctx, req.(*RemoveMixParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_SetMixGain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMixGainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).SetMixGain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_SetMixGain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).SetMixGain(ctx, req.(*SetMixGainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_BridgeSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).BridgeSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_BridgeSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).BridgeSessions(ctx, req.(*BridgeSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_UnbridgeSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbridgeSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).UnbridgeSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_UnbridgeSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).UnbridgeSessions(ctx, req.(*UnbridgeSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_SendDtmf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDtmfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).SendDtmf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_SendDtmf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).SendDtmf(ctx, req.(*SendDtmfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaNode_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MediaNodeServer).Events(m, &grpc.GenericServerStream[EventsRequest, MediaEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaNode_EventsServer = grpc.ServerStreamingServer[MediaEvent]

func _MediaNode_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaNodeServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaNode_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaNodeServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaNode_ServiceDesc is the grpc.ServiceDesc for MediaNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lingvoice.media.v1.MediaNode",
	HandlerType: (*MediaNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _MediaNode_HealthCheck_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _MediaNode_CreateSession_Handler,
		},
		{
			MethodName: "DestroySession",
			Handler:    _MediaNode_DestroySession_Handler,
		},
		{
			MethodName: "AddEndpoint",
			Handler:    _MediaNode_AddEndpoint_Handler,
		},
		{
			MethodName: "RemoveEndpoint",
			Handler:    _MediaNode_RemoveEndpoint_Handler,
		},
		{
			MethodName: "AddTrack",
			Handler:    _MediaNode_AddTrack_Handler,
		},
		{
			MethodName: "RemoveTrack",
			Handler:    _MediaNode_RemoveTrack_Handler,
		},
		{
			MethodName: "StartRecording",
			Handler:    _MediaNode_StartRecording_Handler,
		},
		{
			MethodName: "StopRecording",
			Handler:    _MediaNode_StopRecording_Handler,
		},
		{
			MethodName: "StartMix",
			Handler:    _MediaNode_StartMix_Handler,
		},
		{
			MethodName: "StopMix",
			Handler:    _MediaNode_StopMix_Handler,
		},
		{
			MethodName: "AddMixParticipant",
			Handler:    _MediaNode_AddMixParticipant_Handler,
		},
		{
			MethodName: "RemoveMixParticipant",
			Handler:    _MediaNode_RemoveMixParticipant_Handler,
		},
		{
			MethodName: "SetMixGain",
			Handler:    _MediaNode_SetMixGain_Handler,
		},
		{
			MethodName: "BridgeSessions",
			Handler:    _MediaNode_BridgeSessions_Handler,
		},
		{
			MethodName: "UnbridgeSessions",
			Handler:    _MediaNode_UnbridgeSessions_Handler,
		},
		{
			MethodName: "SendDtmf",
			Handler:    _MediaNode_SendDtmf_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _MediaNode_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushRtp",
			Handler:       _MediaNode_PushRtp_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PullRtp",
			Handler:       _MediaNode_PullRtp_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InjectAudio",
			Handler:       _MediaNode_InjectAudio_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Events",
			Handler:       _MediaNode_Events_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "media_node.proto",
}
