// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: protocol/v1/protocol.proto

package protocolv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProtocolEventSink_OnSipEvent_FullMethodName    = "/lingvoice.protocol.v1.ProtocolEventSink/OnSipEvent"
	ProtocolEventSink_OnWebrtcEvent_FullMethodName = "/lingvoice.protocol.v1.ProtocolEventSink/OnWebrtcEvent"
)

// ProtocolEventSinkClient is the client API for ProtocolEventSink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Rust 媒体面 → Go 控制面：协议事件上报，Go 返回决策
type ProtocolEventSinkClient interface {
	OnSipEvent(ctx context.Context, in *SipEvent, opts ...grpc.CallOption) (*SipDecision, error)
	OnWebrtcEvent(ctx context.Context, in *WebrtcEvent, opts ...grpc.CallOption) (*WebrtcDecision, error)
}

type protocolEventSinkClient struct {
	cc grpc.ClientConnInterface
}

func NewProtocolEventSinkClient(cc grpc.ClientConnInterface) ProtocolEventSinkClient {
	return &protocolEventSinkClient{cc}
}

func (c *protocolEventSinkClient) OnSipEvent(ctx context.Context, in *SipEvent, opts ...grpc.CallOption) (*SipDecision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SipDecision)
	err := c.cc.Invoke(ctx, ProtocolEventSink_OnSipEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolEventSinkClient) OnWebrtcEvent(ctx context.Context, in *WebrtcEvent, opts ...grpc.CallOption) (*WebrtcDecision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebrtcDecision)
	err := c.cc.Invoke(ctx, ProtocolEventSink_OnWebrtcEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtocolEventSinkServer is the server API for ProtocolEventSink service.
// All implementations must embed UnimplementedProtocolEventSinkServer
// for forward compatibility.
//
// Rust 媒体面 → Go 控制面：协议事件上报，Go 返回决策
type ProtocolEventSinkServer interface {
	OnSipEvent(context.Context, *SipEvent) (*SipDecision, error)
	OnWebrtcEvent(context.Context, *WebrtcEvent) (*WebrtcDecision, error)
	mustEmbedUnimplementedProtocolEventSinkServer()
}

// UnimplementedProtocolEventSinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtocolEventSinkServer struct{}

func (UnimplementedProtocolEventSinkServer) OnSipEvent(context.Context, *SipEvent) (*SipDecision, error) {
	return nil, status.Error(codes.Unimplemented, "method OnSipEvent not implemented")
}
func (UnimplementedProtocolEventSinkServer) OnWebrtcEvent(context.Context, *WebrtcEvent) (*WebrtcDecision, error) {
	return nil, status.Error(codes.Unimplemented, "method OnWebrtcEvent not implemented")
}
func (UnimplementedProtocolEventSinkServer) mustEmbedUnimplementedProtocolEventSinkServer() {}
func (UnimplementedProtocolEventSinkServer) testEmbeddedByValue()                           {}

// UnsafeProtocolEventSinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtocolEventSinkServer will
// result in compilation errors.
type UnsafeProtocolEventSinkServer interface {
	mustEmbedUnimplementedProtocolEventSinkServer()
}

func RegisterProtocolEventSinkServer(s grpc.ServiceRegistrar, srv ProtocolEventSinkServer) {
	// If the following call panics, it indicates UnimplementedProtocolEventSinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProtocolEventSink_ServiceDesc, srv)
}

func _ProtocolEventSink_OnSipEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SipEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolEventSinkServer).OnSipEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolEventSink_OnSipEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolEventSinkServer).OnSipEvent(ctx, req.(*SipEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolEventSink_OnWebrtcEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebrtcEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolEventSinkServer).OnWebrtcEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolEventSink_OnWebrtcEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolEventSinkServer).OnWebrtcEvent(ctx, req.(*WebrtcEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// ProtocolEventSink_ServiceDesc is the grpc.ServiceDesc for ProtocolEventSink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtocolEventSink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lingvoice.protocol.v1.ProtocolEventSink",
	HandlerType: (*ProtocolEventSinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnSipEvent",
			Handler:    _ProtocolEventSink_OnSipEvent_Handler,
		},
		{
			MethodName: "OnWebrtcEvent",
			Handler:    _ProtocolEventSink_OnWebrtcEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol/v1/protocol.proto",
}

const (
	ProtocolCommand_SendSipResponse_FullMethodName      = "/lingvoice.protocol.v1.ProtocolCommand/SendSipResponse"
	ProtocolCommand_CreatePeerConnection_FullMethodName = "/lingvoice.protocol.v1.ProtocolCommand/CreatePeerConnection"
	ProtocolCommand_SetRemoteDescription_FullMethodName = "/lingvoice.protocol.v1.ProtocolCommand/SetRemoteDescription"
	ProtocolCommand_AddIceCandidate_FullMethodName      = "/lingvoice.protocol.v1.ProtocolCommand/AddIceCandidate"
	ProtocolCommand_ClosePeerConnection_FullMethodName  = "/lingvoice.protocol.v1.ProtocolCommand/ClosePeerConnection"
)

// ProtocolCommandClient is the client API for ProtocolCommand service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Go 控制面 → Rust 媒体面：协议指令下发
type ProtocolCommandClient interface {
	SendSipResponse(ctx context.Context, in *SipResponse, opts ...grpc.CallOption) (*Ack, error)
	CreatePeerConnection(ctx context.Context, in *CreatePeerConnectionRequest, opts ...grpc.CallOption) (*PeerConnectionId, error)
	SetRemoteDescription(ctx context.Context, in *SetRemoteDescriptionRequest, opts ...grpc.CallOption) (*Ack, error)
	AddIceCandidate(ctx context.Context, in *AddIceCandidateRequest, opts ...grpc.CallOption) (*Ack, error)
	ClosePeerConnection(ctx context.Context, in *ClosePeerConnectionRequest, opts ...grpc.CallOption) (*Ack, error)
}

type protocolCommandClient struct {
	cc grpc.ClientConnInterface
}

func NewProtocolCommandClient(cc grpc.ClientConnInterface) ProtocolCommandClient {
	return &protocolCommandClient{cc}
}

func (c *protocolCommandClient) SendSipResponse(ctx context.Context, in *SipResponse, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ProtocolCommand_SendSipResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolCommandClient) CreatePeerConnection(ctx context.Context, in *CreatePeerConnectionRequest, opts ...grpc.CallOption) (*PeerConnectionId, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerConnectionId)
	err := c.cc.Invoke(ctx, ProtocolCommand_CreatePeerConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolCommandClient) SetRemoteDescription(ctx context.Context, in *SetRemoteDescriptionRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ProtocolCommand_SetRemoteDescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolCommandClient) AddIceCandidate(ctx context.Context, in *AddIceCandidateRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ProtocolCommand_AddIceCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolCommandClient) ClosePeerConnection(ctx context.Context, in *ClosePeerConnectionRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ProtocolCommand_ClosePeerConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtocolCommandServer is the server API for ProtocolCommand service.
// All implementations must embed UnimplementedProtocolCommandServer
// for forward compatibility.
//
// Go 控制面 → Rust 媒体面：协议指令下发
type ProtocolCommandServer interface {
	SendSipResponse(context.Context, *SipResponse) (*Ack, error)
	CreatePeerConnection(context.Context, *CreatePeerConnectionRequest) (*PeerConnectionId, error)
	SetRemoteDescription(context.Context, *SetRemoteDescriptionRequest) (*Ack, error)
	AddIceCandidate(context.Context, *AddIceCandidateRequest) (*Ack, error)
	ClosePeerConnection(context.Context, *ClosePeerConnectionRequest) (*Ack, error)
	mustEmbedUnimplementedProtocolCommandServer()
}

// UnimplementedProtocolCommandServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtocolCommandServer struct{}

func (UnimplementedProtocolCommandServer) SendSipResponse(context.Context, *SipResponse) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSipResponse not implemented")
}
func (UnimplementedProtocolCommandServer) CreatePeerConnection(context.Context, *CreatePeerConnectionRequest) (*PeerConnectionId, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePeerConnection not implemented")
}
func (UnimplementedProtocolCommandServer) SetRemoteDescription(context.Context, *SetRemoteDescriptionRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRemoteDescription not implemented")
}
func (UnimplementedProtocolCommandServer) AddIceCandidate(context.Context, *AddIceCandidateRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method AddIceCandidate not implemented")
}
func (UnimplementedProtocolCommandServer) ClosePeerConnection(context.Context, *ClosePeerConnectionRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ClosePeerConnection not implemented")
}
func (UnimplementedProtocolCommandServer) mustEmbedUnimplementedProtocolCommandServer() {}
func (UnimplementedProtocolCommandServer) testEmbeddedByValue()                         {}

// UnsafeProtocolCommandServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtocolCommandServer will
// result in compilation errors.
type UnsafeProtocolCommandServer interface {
	mustEmbedUnimplementedProtocolCommandServer()
}

func RegisterProtocolCommandServer(s grpc.ServiceRegistrar, srv ProtocolCommandServer) {
	// If the following call panics, it indicates UnimplementedProtocolCommandServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProtocolCommand_ServiceDesc, srv)
}

func _ProtocolCommand_SendSipResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SipResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolCommandServer).SendSipResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolCommand_SendSipResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolCommandServer).SendSipResponse(ctx, req.(*SipResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolCommand_CreatePeerConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePeerConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolCommandServer).CreatePeerConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolCommand_CreatePeerConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolCommandServer).CreatePeerConnection(ctx, req.(*CreatePeerConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolCommand_SetRemoteDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRemoteDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolCommandServer).SetRemoteDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolCommand_SetRemoteDescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolCommandServer).SetRemoteDescription(ctx, req.(*SetRemoteDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolCommand_AddIceCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIceCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolCommandServer).AddIceCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolCommand_AddIceCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolCommandServer).AddIceCandidate(ctx, req.(*AddIceCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolCommand_ClosePeerConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosePeerConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolCommandServer).ClosePeerConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolCommand_ClosePeerConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolCommandServer).ClosePeerConnection(ctx, req.(*ClosePeerConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProtocolCommand_ServiceDesc is the grpc.ServiceDesc for ProtocolCommand service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtocolCommand_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lingvoice.protocol.v1.ProtocolCommand",
	HandlerType: (*ProtocolCommandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSipResponse",
			Handler:    _ProtocolCommand_SendSipResponse_Handler,
		},
		{
			MethodName: "CreatePeerConnection",
			Handler:    _ProtocolCommand_CreatePeerConnection_Handler,
		},
		{
			MethodName: "SetRemoteDescription",
			Handler:    _ProtocolCommand_SetRemoteDescription_Handler,
		},
		{
			MethodName: "AddIceCandidate",
			Handler:    _ProtocolCommand_AddIceCandidate_Handler,
		},
		{
			MethodName: "ClosePeerConnection",
			Handler:    _ProtocolCommand_ClosePeerConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol/v1/protocol.proto",
}
