// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: protocol/v1/protocol.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SipMethod int32

const (
	SipMethod_SIP_METHOD_UNSPECIFIED SipMethod = 0
	SipMethod_SIP_METHOD_INVITE      SipMethod = 1
	SipMethod_SIP_METHOD_BYE         SipMethod = 2
	SipMethod_SIP_METHOD_REGISTER    SipMethod = 3
	SipMethod_SIP_METHOD_ACK         SipMethod = 4
	SipMethod_SIP_METHOD_CANCEL      SipMethod = 5
	SipMethod_SIP_METHOD_OPTIONS     SipMethod = 6
)

// Enum value maps for SipMethod.
var (
	SipMethod_name = map[int32]string{
		0: "SIP_METHOD_UNSPECIFIED",
		1: "SIP_METHOD_INVITE",
		2: "SIP_METHOD_BYE",
		3: "SIP_METHOD_REGISTER",
		4: "SIP_METHOD_ACK",
		5: "SIP_METHOD_CANCEL",
		6: "SIP_METHOD_OPTIONS",
	}
	SipMethod_value = map[string]int32{
		"SIP_METHOD_UNSPECIFIED": 0,
		"SIP_METHOD_INVITE":      1,
		"SIP_METHOD_BYE":         2,
		"SIP_METHOD_REGISTER":    3,
		"SIP_METHOD_ACK":         4,
		"SIP_METHOD_CANCEL":      5,
		"SIP_METHOD_OPTIONS":     6,
	}
)

func (x SipMethod) Enum() *SipMethod {
	p := new(SipMethod)
	*p = x
	return p
}

func (x SipMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SipMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_v1_protocol_proto_enumTypes[0].Descriptor()
}

func (SipMethod) Type() protoreflect.EnumType {
	return &file_protocol_v1_protocol_proto_enumTypes[0]
}

func (x SipMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SipMethod.Descriptor instead.
func (SipMethod) EnumDescriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{0}
}

type SipAction int32

const (
	SipAction_SIP_ACTION_UNSPECIFIED SipAction = 0
	SipAction_SIP_ACTION_SEND_401    SipAction = 1
	SipAction_SIP_ACTION_SEND_407    SipAction = 2
	SipAction_SIP_ACTION_SEND_180    SipAction = 3
	SipAction_SIP_ACTION_SEND_200_OK SipAction = 4
	SipAction_SIP_ACTION_SEND_486    SipAction = 5
	SipAction_SIP_ACTION_SEND_603    SipAction = 6
	SipAction_SIP_ACTION_SEND_404    SipAction = 7
	SipAction_SIP_ACTION_ACK         SipAction = 8
	SipAction_SIP_ACTION_REJECT      SipAction = 9
)

// Enum value maps for SipAction.
var (
	SipAction_name = map[int32]string{
		0: "SIP_ACTION_UNSPECIFIED",
		1: "SIP_ACTION_SEND_401",
		2: "SIP_ACTION_SEND_407",
		3: "SIP_ACTION_SEND_180",
		4: "SIP_ACTION_SEND_200_OK",
		5: "SIP_ACTION_SEND_486",
		6: "SIP_ACTION_SEND_603",
		7: "SIP_ACTION_SEND_404",
		8: "SIP_ACTION_ACK",
		9: "SIP_ACTION_REJECT",
	}
	SipAction_value = map[string]int32{
		"SIP_ACTION_UNSPECIFIED": 0,
		"SIP_ACTION_SEND_401":    1,
		"SIP_ACTION_SEND_407":    2,
		"SIP_ACTION_SEND_180":    3,
		"SIP_ACTION_SEND_200_OK": 4,
		"SIP_ACTION_SEND_486":    5,
		"SIP_ACTION_SEND_603":    6,
		"SIP_ACTION_SEND_404":    7,
		"SIP_ACTION_ACK":         8,
		"SIP_ACTION_REJECT":      9,
	}
)

func (x SipAction) Enum() *SipAction {
	p := new(SipAction)
	*p = x
	return p
}

func (x SipAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SipAction) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_v1_protocol_proto_enumTypes[1].Descriptor()
}

func (SipAction) Type() protoreflect.EnumType {
	return &file_protocol_v1_protocol_proto_enumTypes[1]
}

func (x SipAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SipAction.Descriptor instead.
func (SipAction) EnumDescriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{1}
}

type WebrtcRole int32

const (
	WebrtcRole_WEBRTC_ROLE_UNSPECIFIED WebrtcRole = 0
	WebrtcRole_WEBRTC_ROLE_PUBLISHER   WebrtcRole = 1
	WebrtcRole_WEBRTC_ROLE_SUBSCRIBER  WebrtcRole = 2
)

// Enum value maps for WebrtcRole.
var (
	WebrtcRole_name = map[int32]string{
		0: "WEBRTC_ROLE_UNSPECIFIED",
		1: "WEBRTC_ROLE_PUBLISHER",
		2: "WEBRTC_ROLE_SUBSCRIBER",
	}
	WebrtcRole_value = map[string]int32{
		"WEBRTC_ROLE_UNSPECIFIED": 0,
		"WEBRTC_ROLE_PUBLISHER":   1,
		"WEBRTC_ROLE_SUBSCRIBER":  2,
	}
)

func (x WebrtcRole) Enum() *WebrtcRole {
	p := new(WebrtcRole)
	*p = x
	return p
}

func (x WebrtcRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebrtcRole) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_v1_protocol_proto_enumTypes[2].Descriptor()
}

func (WebrtcRole) Type() protoreflect.EnumType {
	return &file_protocol_v1_protocol_proto_enumTypes[2]
}

func (x WebrtcRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebrtcRole.Descriptor instead.
func (WebrtcRole) EnumDescriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{2}
}

type WebrtcEventType int32

const (
	WebrtcEventType_WEBRTC_EVENT_UNSPECIFIED WebrtcEventType = 0
	WebrtcEventType_WEBRTC_EVENT_OFFER       WebrtcEventType = 1
	WebrtcEventType_WEBRTC_EVENT_ANSWER      WebrtcEventType = 2
	WebrtcEventType_WEBRTC_EVENT_CANDIDATE   WebrtcEventType = 3
	WebrtcEventType_WEBRTC_EVENT_CONNECTED   WebrtcEventType = 4
	WebrtcEventType_WEBRTC_EVENT_FAILED      WebrtcEventType = 5
	WebrtcEventType_WEBRTC_EVENT_CLOSED      WebrtcEventType = 6
	WebrtcEventType_WEBRTC_EVENT_ICE_RESTART WebrtcEventType = 7
)

// Enum value maps for WebrtcEventType.
var (
	WebrtcEventType_name = map[int32]string{
		0: "WEBRTC_EVENT_UNSPECIFIED",
		1: "WEBRTC_EVENT_OFFER",
		2: "WEBRTC_EVENT_ANSWER",
		3: "WEBRTC_EVENT_CANDIDATE",
		4: "WEBRTC_EVENT_CONNECTED",
		5: "WEBRTC_EVENT_FAILED",
		6: "WEBRTC_EVENT_CLOSED",
		7: "WEBRTC_EVENT_ICE_RESTART",
	}
	WebrtcEventType_value = map[string]int32{
		"WEBRTC_EVENT_UNSPECIFIED": 0,
		"WEBRTC_EVENT_OFFER":       1,
		"WEBRTC_EVENT_ANSWER":      2,
		"WEBRTC_EVENT_CANDIDATE":   3,
		"WEBRTC_EVENT_CONNECTED":   4,
		"WEBRTC_EVENT_FAILED":      5,
		"WEBRTC_EVENT_CLOSED":      6,
		"WEBRTC_EVENT_ICE_RESTART": 7,
	}
)

func (x WebrtcEventType) Enum() *WebrtcEventType {
	p := new(WebrtcEventType)
	*p = x
	return p
}

func (x WebrtcEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebrtcEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_v1_protocol_proto_enumTypes[3].Descriptor()
}

func (WebrtcEventType) Type() protoreflect.EnumType {
	return &file_protocol_v1_protocol_proto_enumTypes[3]
}

func (x WebrtcEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebrtcEventType.Descriptor instead.
func (WebrtcEventType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{3}
}

type WebrtcAction int32

const (
	WebrtcAction_WEBRTC_ACTION_UNSPECIFIED            WebrtcAction = 0
	WebrtcAction_WEBRTC_ACTION_CREATE_PEER_CONNECTION WebrtcAction = 1
	WebrtcAction_WEBRTC_ACTION_SET_REMOTE_DESCRIPTION WebrtcAction = 2
	WebrtcAction_WEBRTC_ACTION_ADD_ICE_CANDIDATE      WebrtcAction = 3
	WebrtcAction_WEBRTC_ACTION_SEND_OFFER             WebrtcAction = 4
	WebrtcAction_WEBRTC_ACTION_SEND_ANSWER            WebrtcAction = 5
	WebrtcAction_WEBRTC_ACTION_CLOSE_PEER_CONNECTION  WebrtcAction = 6
)

// Enum value maps for WebrtcAction.
var (
	WebrtcAction_name = map[int32]string{
		0: "WEBRTC_ACTION_UNSPECIFIED",
		1: "WEBRTC_ACTION_CREATE_PEER_CONNECTION",
		2: "WEBRTC_ACTION_SET_REMOTE_DESCRIPTION",
		3: "WEBRTC_ACTION_ADD_ICE_CANDIDATE",
		4: "WEBRTC_ACTION_SEND_OFFER",
		5: "WEBRTC_ACTION_SEND_ANSWER",
		6: "WEBRTC_ACTION_CLOSE_PEER_CONNECTION",
	}
	WebrtcAction_value = map[string]int32{
		"WEBRTC_ACTION_UNSPECIFIED":            0,
		"WEBRTC_ACTION_CREATE_PEER_CONNECTION": 1,
		"WEBRTC_ACTION_SET_REMOTE_DESCRIPTION": 2,
		"WEBRTC_ACTION_ADD_ICE_CANDIDATE":      3,
		"WEBRTC_ACTION_SEND_OFFER":             4,
		"WEBRTC_ACTION_SEND_ANSWER":            5,
		"WEBRTC_ACTION_CLOSE_PEER_CONNECTION":  6,
	}
)

func (x WebrtcAction) Enum() *WebrtcAction {
	p := new(WebrtcAction)
	*p = x
	return p
}

func (x WebrtcAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebrtcAction) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_v1_protocol_proto_enumTypes[4].Descriptor()
}

func (WebrtcAction) Type() protoreflect.EnumType {
	return &file_protocol_v1_protocol_proto_enumTypes[4]
}

func (x WebrtcAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebrtcAction.Descriptor instead.
func (WebrtcAction) EnumDescriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{4}
}

type SipEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	FromAddr      string                 `protobuf:"bytes,2,opt,name=from_addr,json=fromAddr,proto3" json:"from_addr,omitempty"`
	ToAddr        string                 `protobuf:"bytes,3,opt,name=to_addr,json=toAddr,proto3" json:"to_addr,omitempty"`
	Method        SipMethod              `protobuf:"varint,4,opt,name=method,proto3,enum=lingvoice.protocol.v1.SipMethod" json:"method,omitempty"`
	AuthHeader    string                 `protobuf:"bytes,5,opt,name=auth_header,json=authHeader,proto3" json:"auth_header,omitempty"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"` // SDP body
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SipEvent) Reset() {
	*x = SipEvent{}
	mi := &file_protocol_v1_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SipEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SipEvent) ProtoMessage() {}

func (x *SipEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SipEvent.ProtoReflect.Descriptor instead.
func (*SipEvent) Descriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *SipEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *SipEvent) GetFromAddr() string {
	if x != nil {
		return x.FromAddr
	}
	return ""
}

func (x *SipEvent) GetToAddr() string {
	if x != nil {
		return x.ToAddr
	}
	return ""
}

func (x *SipEvent) GetMethod() SipMethod {
	if x != nil {
		return x.Method
	}
	return SipMethod_SIP_METHOD_UNSPECIFIED
}

func (x *SipEvent) GetAuthHeader() string {
	if x != nil {
		return x.AuthHeader
	}
	return ""
}

func (x *SipEvent) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type SipDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        SipAction              `protobuf:"varint,1,opt,name=action,proto3,enum=lingvoice.protocol.v1.SipAction" json:"action,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RouteTo       string                 `protobuf:"bytes,3,opt,name=route_to,json=routeTo,proto3" json:"route_to,omitempty"`
	LocalRtpPort  uint32                 `protobuf:"varint,4,opt,name=local_rtp_port,json=localRtpPort,proto3" json:"local_rtp_port,omitempty"`
	Codec         string                 `protobuf:"bytes,5,opt,name=codec,proto3" json:"codec,omitempty"`
	SampleRate    uint32                 `protobuf:"varint,6,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels      uint32                 `protobuf:"varint,7,opt,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SipDecision) Reset() {
	*x = SipDecision{}
	mi := &file_protocol_v1_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SipDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SipDecision) ProtoMessage() {}

func (x *SipDecision) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SipDecision.ProtoReflect.Descriptor instead.
func (*SipDecision) Descriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *SipDecision) GetAction() SipAction {
	if x != nil {
		return x.Action
	}
	return SipAction_SIP_ACTION_UNSPECIFIED
}

func (x *SipDecision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SipDecision) GetRouteTo() string {
	if x != nil {
		return x.RouteTo
	}
	return ""
}

func (x *SipDecision) GetLocalRtpPort() uint32 {
	if x != nil {
		return x.LocalRtpPort
	}
	return 0
}

func (x *SipDecision) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *SipDecision) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *SipDecision) GetChannels() uint32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

type SipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Status        uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"` // SDP body
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SipResponse) Reset() {
	*x = SipResponse{}
	mi := &file_protocol_v1_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SipResponse) ProtoMessage() {}

func (x *SipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SipResponse.ProtoReflect.Descriptor instead.
func (*SipResponse) Descriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *SipResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *SipResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SipResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SipResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type SdpDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "offer" | "answer"
	Sdp           string                 `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SdpDescription) Reset() {
	*x = SdpDescription{}
	mi := &file_protocol_v1_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SdpDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdpDescription) ProtoMessage() {}

func (x *SdpDescription) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdpDescription.ProtoReflect.Descriptor instead.
func (*SdpDescription) Descriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *SdpDescription) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SdpDescription) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type IceCandidate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Candidate        string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid           string                 `protobuf:"bytes,2,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMLineIndex    int32                  `protobuf:"varint,3,opt,name=sdp_m_line_index,json=sdpMLineIndex,proto3" json:"sdp_m_line_index,omitempty"`
	UsernameFragment string                 `protobuf:"bytes,4,opt,name=username_fragment,json=usernameFragment,proto3" json:"username_fragment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IceCandidate) Reset() {
	*x = IceCandidate{}
	mi := &file_protocol_v1_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IceCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceCandidate) ProtoMessage() {}

func (x *IceCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceCandidate.ProtoReflect.Descriptor instead.
func (*IceCandidate) Descriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *IceCandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *IceCandidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *IceCandidate) GetSdpMLineIndex() int32 {
	if x != nil {
		return x.SdpMLineIndex
	}
	return 0
}

func (x *IceCandidate) GetUsernameFragment() string {
	if x != nil {
		return x.UsernameFragment
	}
	return ""
}

type WebrtcEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PcId          string                 `protobuf:"bytes,2,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	Role          WebrtcRole             `protobuf:"varint,3,opt,name=role,proto3,enum=lingvoice.protocol.v1.WebrtcRole" json:"role,omitempty"`
	EventType     WebrtcEventType        `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3,enum=lingvoice.protocol.v1.WebrtcEventType" json:"event_type,omitempty"`
	Sdp           *SdpDescription        `protobuf:"bytes,5,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Candidate     *IceCandidate          `protobuf:"bytes,6,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebrtcEvent) Reset() {
	*x = WebrtcEvent{}
	mi := &file_protocol_v1_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebrtcEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebrtcEvent) ProtoMessage() {}

func (x *WebrtcEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebrtcEvent.ProtoReflect.Descriptor instead.
func (*WebrtcEvent) Descriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *WebrtcEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WebrtcEvent) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

func (x *WebrtcEvent) GetRole() WebrtcRole {
	if x != nil {
		return x.Role
	}
	return WebrtcRole_WEBRTC_ROLE_UNSPECIFIED
}

func (x *WebrtcEvent) GetEventType() WebrtcEventType {
	if x != nil {
		return x.EventType
	}
	return WebrtcEventType_WEBRTC_EVENT_UNSPECIFIED
}

func (x *WebrtcEvent) GetSdp() *SdpDescription {
	if x != nil {
		return x.Sdp
	}
	return nil
}

func (x *WebrtcEvent) GetCandidate() *IceCandidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *WebrtcEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WebrtcDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        WebrtcAction           `protobuf:"varint,1,opt,name=action,proto3,enum=lingvoice.protocol.v1.WebrtcAction" json:"action,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PcId          string                 `protobuf:"bytes,3,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	Sdp           *SdpDescription        `protobuf:"bytes,4,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Candidate     *IceCandidate          `protobuf:"bytes,5,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebrtcDecision) Reset() {
	*x = WebrtcDecision{}
	mi := &file_protocol_v1_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebrtcDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebrtcDecision) ProtoMessage() {}

func (x *WebrtcDecision) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebrtcDecision.ProtoReflect.Descriptor instead.
func (*WebrtcDecision) Descriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *WebrtcDecision) GetAction() WebrtcAction {
	if x != nil {
		return x.Action
	}
	return WebrtcAction_WEBRTC_ACTION_UNSPECIFIED
}

func (x *WebrtcDecision) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WebrtcDecision) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

func (x *WebrtcDecision) GetSdp() *SdpDescription {
	if x != nil {
		return x.Sdp
	}
	return nil
}

func (x *WebrtcDecision) GetCandidate() *IceCandidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_protocol_v1_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PeerConnectionId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcId          string                 `protobuf:"bytes,1,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerConnectionId) Reset() {
	*x = PeerConnectionId{}
	mi := &file_protocol_v1_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerConnectionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerConnectionId) ProtoMessage() {}

func (x *PeerConnectionId) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerConnectionId.ProtoReflect.Descriptor instead.
func (*PeerConnectionId) Descriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *PeerConnectionId) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

type CreatePeerConnectionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IceServers      []string               `protobuf:"bytes,2,rep,name=ice_servers,json=iceServers,proto3" json:"ice_servers,omitempty"`
	EnableSimulcast bool                   `protobuf:"varint,3,opt,name=enable_simulcast,json=enableSimulcast,proto3" json:"enable_simulcast,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePeerConnectionRequest) Reset() {
	*x = CreatePeerConnectionRequest{}
	mi := &file_protocol_v1_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeerConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeerConnectionRequest) ProtoMessage() {}

func (x *CreatePeerConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeerConnectionRequest.ProtoReflect.Descriptor instead.
func (*CreatePeerConnectionRequest) Descriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePeerConnectionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreatePeerConnectionRequest) GetIceServers() []string {
	if x != nil {
		return x.IceServers
	}
	return nil
}

func (x *CreatePeerConnectionRequest) GetEnableSimulcast() bool {
	if x != nil {
		return x.EnableSimulcast
	}
	return false
}

type SetRemoteDescriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcId          string                 `protobuf:"bytes,1,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	Sdp           *SdpDescription        `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRemoteDescriptionRequest) Reset() {
	*x = SetRemoteDescriptionRequest{}
	mi := &file_protocol_v1_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRemoteDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRemoteDescriptionRequest) ProtoMessage() {}

func (x *SetRemoteDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRemoteDescriptionRequest.ProtoReflect.Descriptor instead.
func (*SetRemoteDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *SetRemoteDescriptionRequest) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

func (x *SetRemoteDescriptionRequest) GetSdp() *SdpDescription {
	if x != nil {
		return x.Sdp
	}
	return nil
}

type AddIceCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcId          string                 `protobuf:"bytes,1,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	Candidate     *IceCandidate          `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddIceCandidateRequest) Reset() {
	*x = AddIceCandidateRequest{}
	mi := &file_protocol_v1_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddIceCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIceCandidateRequest) ProtoMessage() {}

func (x *AddIceCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIceCandidateRequest.ProtoReflect.Descriptor instead.
func (*AddIceCandidateRequest) Descriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *AddIceCandidateRequest) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

func (x *AddIceCandidateRequest) GetCandidate() *IceCandidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

type ClosePeerConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcId          string                 `protobuf:"bytes,1,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosePeerConnectionRequest) Reset() {
	*x = ClosePeerConnectionRequest{}
	mi := &file_protocol_v1_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosePeerConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosePeerConnectionRequest) ProtoMessage() {}

func (x *ClosePeerConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosePeerConnectionRequest.ProtoReflect.Descriptor instead.
func (*ClosePeerConnectionRequest) Descriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *ClosePeerConnectionRequest) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

var File_protocol_v1_protocol_proto protoreflect.FileDescriptor

const file_protocol_v1_protocol_proto_rawDesc = "" +
	"\n" +
	"\x1aprotocol/v1/protocol.proto\x12\x15lingvoice.protocol.v1\"\xc8\x01\n" +
	"\bSipEvent\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\tfrom_addr\x18\x02 \x01(\tR\bfromAddr\x12\x17\n" +
	"\ato_addr\x18\x03 \x01(\tR\x06toAddr\x128\n" +
	"\x06method\x18\x04 \x01(\x0e2 .lingvoice.protocol.v1.SipMethodR\x06method\x12\x1f\n" +
	"\vauth_header\x18\x05 \x01(\tR\n" +
	"authHeader\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\"\xf3\x01\n" +
	"\vSipDecision\x128\n" +
	"\x06action\x18\x01 \x01(\x0e2 .lingvoice.protocol.v1.SipActionR\x06action\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x19\n" +
	"\broute_to\x18\x03 \x01(\tR\arouteTo\x12$\n" +
	"\x0elocal_rtp_port\x18\x04 \x01(\rR\flocalRtpPort\x12\x14\n" +
	"\x05codec\x18\x05 \x01(\tR\x05codec\x12\x1f\n" +
	"\vsample_rate\x18\x06 \x01(\rR\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\a \x01(\rR\bchannels\"j\n" +
	"\vSipResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\"6\n" +
	"\x0eSdpDescription\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03sdp\x18\x02 \x01(\tR\x03sdp\"\x9b\x01\n" +
	"\fIceCandidate\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x02 \x01(\tR\x06sdpMid\x12'\n" +
	"\x10sdp_m_line_index\x18\x03 \x01(\x05R\rsdpMLineIndex\x12+\n" +
	"\x11username_fragment\x18\x04 \x01(\tR\x10usernameFragment\"\xd1\x02\n" +
	"\vWebrtcEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x13\n" +
	"\x05pc_id\x18\x02 \x01(\tR\x04pcId\x125\n" +
	"\x04role\x18\x03 \x01(\x0e2!.lingvoice.protocol.v1.WebrtcRoleR\x04role\x12E\n" +
	"\n" +
	"event_type\x18\x04 \x01(\x0e2&.lingvoice.protocol.v1.WebrtcEventTypeR\teventType\x127\n" +
	"\x03sdp\x18\x05 \x01(\v2%.lingvoice.protocol.v1.SdpDescriptionR\x03sdp\x12A\n" +
	"\tcandidate\x18\x06 \x01(\v2#.lingvoice.protocol.v1.IceCandidateR\tcandidate\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\xfd\x01\n" +
	"\x0eWebrtcDecision\x12;\n" +
	"\x06action\x18\x01 \x01(\x0e2#.lingvoice.protocol.v1.WebrtcActionR\x06action\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x13\n" +
	"\x05pc_id\x18\x03 \x01(\tR\x04pcId\x127\n" +
	"\x03sdp\x18\x04 \x01(\v2%.lingvoice.protocol.v1.SdpDescriptionR\x03sdp\x12A\n" +
	"\tcandidate\x18\x05 \x01(\v2#.lingvoice.protocol.v1.IceCandidateR\tcandidate\"+\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"'\n" +
	"\x10PeerConnectionId\x12\x13\n" +
	"\x05pc_id\x18\x01 \x01(\tR\x04pcId\"\x88\x01\n" +
	"\x1bCreatePeerConnectionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vice_servers\x18\x02 \x03(\tR\n" +
	"iceServers\x12)\n" +
	"\x10enable_simulcast\x18\x03 \x01(\bR\x0fenableSimulcast\"k\n" +
	"\x1bSetRemoteDescriptionRequest\x12\x13\n" +
	"\x05pc_id\x18\x01 \x01(\tR\x04pcId\x127\n" +
	"\x03sdp\x18\x02 \x01(\v2%.lingvoice.protocol.v1.SdpDescriptionR\x03sdp\"p\n" +
	"\x16AddIceCandidateRequest\x12\x13\n" +
	"\x05pc_id\x18\x01 \x01(\tR\x04pcId\x12A\n" +
	"\tcandidate\x18\x02 \x01(\v2#.lingvoice.protocol.v1.IceCandidateR\tcandidate\"1\n" +
	"\x1aClosePeerConnectionRequest\x12\x13\n" +
	"\x05pc_id\x18\x01 \x01(\tR\x04pcId*\xae\x01\n" +
	"\tSipMethod\x12\x1a\n" +
	"\x16SIP_METHOD_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SIP_METHOD_INVITE\x10\x01\x12\x12\n" +
	"\x0eSIP_METHOD_BYE\x10\x02\x12\x17\n" +
	"\x13SIP_METHOD_REGISTER\x10\x03\x12\x12\n" +
	"\x0eSIP_METHOD_ACK\x10\x04\x12\x15\n" +
	"\x11SIP_METHOD_CANCEL\x10\x05\x12\x16\n" +
	"\x12SIP_METHOD_OPTIONS\x10\x06*\x84\x02\n" +
	"\tSipAction\x12\x1a\n" +
	"\x16SIP_ACTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SIP_ACTION_SEND_401\x10\x01\x12\x17\n" +
	"\x13SIP_ACTION_SEND_407\x10\x02\x12\x17\n" +
	"\x13SIP_ACTION_SEND_180\x10\x03\x12\x1a\n" +
	"\x16SIP_ACTION_SEND_200_OK\x10\x04\x12\x17\n" +
	"\x13SIP_ACTION_SEND_486\x10\x05\x12\x17\n" +
	"\x13SIP_ACTION_SEND_603\x10\x06\x12\x17\n" +
	"\x13SIP_ACTION_SEND_404\x10\a\x12\x12\n" +
	"\x0eSIP_ACTION_ACK\x10\b\x12\x15\n" +
	"\x11SIP_ACTION_REJECT\x10\t*`\n" +
	"\n" +
	"WebrtcRole\x12\x1b\n" +
	"\x17WEBRTC_ROLE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15WEBRTC_ROLE_PUBLISHER\x10\x01\x12\x1a\n" +
	"\x16WEBRTC_ROLE_SUBSCRIBER\x10\x02*\xe8\x01\n" +
	"\x0fWebrtcEventType\x12\x1c\n" +
	"\x18WEBRTC_EVENT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12WEBRTC_EVENT_OFFER\x10\x01\x12\x17\n" +
	"\x13WEBRTC_EVENT_ANSWER\x10\x02\x12\x1a\n" +
	"\x16WEBRTC_EVENT_CANDIDATE\x10\x03\x12\x1a\n" +
	"\x16WEBRTC_EVENT_CONNECTED\x10\x04\x12\x17\n" +
	"\x13WEBRTC_EVENT_FAILED\x10\x05\x12\x17\n" +
	"\x13WEBRTC_EVENT_CLOSED\x10\x06\x12\x1c\n" +
	"\x18WEBRTC_EVENT_ICE_RESTART\x10\a*\x8c\x02\n" +
	"\fWebrtcAction\x12\x1d\n" +
	"\x19WEBRTC_ACTION_UNSPECIFIED\x10\x00\x12(\n" +
	"$WEBRTC_ACTION_CREATE_PEER_CONNECTION\x10\x01\x12(\n" +
	"$WEBRTC_ACTION_SET_REMOTE_DESCRIPTION\x10\x02\x12#\n" +
	"\x1fWEBRTC_ACTION_ADD_ICE_CANDIDATE\x10\x03\x12\x1c\n" +
	"\x18WEBRTC_ACTION_SEND_OFFER\x10\x04\x12\x1d\n" +
	"\x19WEBRTC_ACTION_SEND_ANSWER\x10\x05\x12'\n" +
	"#WEBRTC_ACTION_CLOSE_PEER_CONNECTION\x10\x062\xc2\x01\n" +
	"\x11ProtocolEventSink\x12Q\n" +
	"\n" +
	"OnSipEvent\x12\x1f.lingvoice.protocol.v1.SipEvent\x1a\".lingvoice.protocol.v1.SipDecision\x12Z\n" +
	"\rOnWebrtcEvent\x12\".lingvoice.protocol.v1.WebrtcEvent\x1a%.lingvoice.protocol.v1.WebrtcDecision2\x85\x04\n" +
	"\x0fProtocolCommand\x12Q\n" +
	"\x0fSendSipResponse\x12\".lingvoice.protocol.v1.SipResponse\x1a\x1a.lingvoice.protocol.v1.Ack\x12s\n" +
	"\x14CreatePeerConnection\x122.lingvoice.protocol.v1.CreatePeerConnectionRequest\x1a'.lingvoice.protocol.v1.PeerConnectionId\x12f\n" +
	"\x14SetRemoteDescription\x122.lingvoice.protocol.v1.SetRemoteDescriptionRequest\x1a\x1a.lingvoice.protocol.v1.Ack\x12\\\n" +
	"\x0fAddIceCandidate\x12-.lingvoice.protocol.v1.AddIceCandidateRequest\x1a\x1a.lingvoice.protocol.v1.Ack\x12d\n" +
	"\x13ClosePeerConnection\x121.lingvoice.protocol.v1.ClosePeerConnectionRequest\x1a\x1a.lingvoice.protocol.v1.AckB<Z:github.com/LingByte/LingVoice/proto/protocol/v1;protocolv1b\x06proto3"

var (
	file_protocol_v1_protocol_proto_rawDescOnce sync.Once
	file_protocol_v1_protocol_proto_rawDescData []byte
)

func file_protocol_v1_protocol_proto_rawDescGZIP() []byte {
	file_protocol_v1_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_v1_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_v1_protocol_proto_rawDesc), len(file_protocol_v1_protocol_proto_rawDesc)))
	})
	return file_protocol_v1_protocol_proto_rawDescData
}

var file_protocol_v1_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_protocol_v1_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protocol_v1_protocol_proto_goTypes = []any{
	(SipMethod)(0),                      // 0: lingvoice.protocol.v1.SipMethod
	(SipAction)(0),                      // 1: lingvoice.protocol.v1.SipAction
	(WebrtcRole)(0),                     // 2: lingvoice.protocol.v1.WebrtcRole
	(WebrtcEventType)(0),                // 3: lingvoice.protocol.v1.WebrtcEventType
	(WebrtcAction)(0),                   // 4: lingvoice.protocol.v1.WebrtcAction
	(*SipEvent)(nil),                    // 5: lingvoice.protocol.v1.SipEvent
	(*SipDecision)(nil),                 // 6: lingvoice.protocol.v1.SipDecision
	(*SipResponse)(nil),                 // 7: lingvoice.protocol.v1.SipResponse
	(*SdpDescription)(nil),              // 8: lingvoice.protocol.v1.SdpDescription
	(*IceCandidate)(nil),                // 9: lingvoice.protocol.v1.IceCandidate
	(*WebrtcEvent)(nil),                 // 10: lingvoice.protocol.v1.WebrtcEvent
	(*WebrtcDecision)(nil),              // 11: lingvoice.protocol.v1.WebrtcDecision
	(*Ack)(nil),                         // 12: lingvoice.protocol.v1.Ack
	(*PeerConnectionId)(nil),            // 13: lingvoice.protocol.v1.PeerConnectionId
	(*CreatePeerConnectionRequest)(nil), // 14: lingvoice.protocol.v1.CreatePeerConnectionRequest
	(*SetRemoteDescriptionRequest)(nil), // 15: lingvoice.protocol.v1.SetRemoteDescriptionRequest
	(*AddIceCandidateRequest)(nil),      // 16: lingvoice.protocol.v1.AddIceCandidateRequest
	(*ClosePeerConnectionRequest)(nil),  // 17: lingvoice.protocol.v1.ClosePeerConnectionRequest
}
var file_protocol_v1_protocol_proto_depIdxs = []int32{
	0,  // 0: lingvoice.protocol.v1.SipEvent.method:type_name -> lingvoice.protocol.v1.SipMethod
	1,  // 1: lingvoice.protocol.v1.SipDecision.action:type_name -> lingvoice.protocol.v1.SipAction
	2,  // 2: lingvoice.protocol.v1.WebrtcEvent.role:type_name -> lingvoice.protocol.v1.WebrtcRole
	3,  // 3: lingvoice.protocol.v1.WebrtcEvent.event_type:type_name -> lingvoice.protocol.v1.WebrtcEventType
	8,  // 4: lingvoice.protocol.v1.WebrtcEvent.sdp:type_name -> lingvoice.protocol.v1.SdpDescription
	9,  // 5: lingvoice.protocol.v1.WebrtcEvent.candidate:type_name -> lingvoice.protocol.v1.IceCandidate
	4,  // 6: lingvoice.protocol.v1.WebrtcDecision.action:type_name -> lingvoice.protocol.v1.WebrtcAction
	8,  // 7: lingvoice.protocol.v1.WebrtcDecision.sdp:type_name -> lingvoice.protocol.v1.SdpDescription
	9,  // 8: lingvoice.protocol.v1.WebrtcDecision.candidate:type_name -> lingvoice.protocol.v1.IceCandidate
	8,  // 9: lingvoice.protocol.v1.SetRemoteDescriptionRequest.sdp:type_name -> lingvoice.protocol.v1.SdpDescription
	9,  // 10: lingvoice.protocol.v1.AddIceCandidateRequest.candidate:type_name -> lingvoice.protocol.v1.IceCandidate
	5,  // 11: lingvoice.protocol.v1.ProtocolEventSink.OnSipEvent:input_type -> lingvoice.protocol.v1.SipEvent
	10, // 12: lingvoice.protocol.v1.ProtocolEventSink.OnWebrtcEvent:input_type -> lingvoice.protocol.v1.WebrtcEvent
	7,  // 13: lingvoice.protocol.v1.ProtocolCommand.SendSipResponse:input_type -> lingvoice.protocol.v1.SipResponse
	14, // 14: lingvoice.protocol.v1.ProtocolCommand.CreatePeerConnection:input_type -> lingvoice.protocol.v1.CreatePeerConnectionRequest
	15, // 15: lingvoice.protocol.v1.ProtocolCommand.SetRemoteDescription:input_type -> lingvoice.protocol.v1.SetRemoteDescriptionRequest
	16, // 16: lingvoice.protocol.v1.ProtocolCommand.AddIceCandidate:input_type -> lingvoice.protocol.v1.AddIceCandidateRequest
	17, // 17: lingvoice.protocol.v1.ProtocolCommand.ClosePeerConnection:input_type -> lingvoice.protocol.v1.ClosePeerConnectionRequest
	6,  // 18: lingvoice.protocol.v1.ProtocolEventSink.OnSipEvent:output_type -> lingvoice.protocol.v1.SipDecision
	11, // 19: lingvoice.protocol.v1.ProtocolEventSink.OnWebrtcEvent:output_type -> lingvoice.protocol.v1.WebrtcDecision
	12, // 20: lingvoice.protocol.v1.ProtocolCommand.SendSipResponse:output_type -> lingvoice.protocol.v1.Ack
	13, // 21: lingvoice.protocol.v1.ProtocolCommand.CreatePeerConnection:output_type -> lingvoice.protocol.v1.PeerConnectionId
	12, // 22: lingvoice.protocol.v1.ProtocolCommand.SetRemoteDescription:output_type -> lingvoice.protocol.v1.Ack
	12, // 23: lingvoice.protocol.v1.ProtocolCommand.AddIceCandidate:output_type -> lingvoice.protocol.v1.Ack
	12, // 24: lingvoice.protocol.v1.ProtocolCommand.ClosePeerConnection:output_type -> lingvoice.protocol.v1.Ack
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_protocol_v1_protocol_proto_init() }
func file_protocol_v1_protocol_proto_init() {
	if File_protocol_v1_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_v1_protocol_proto_rawDesc), len(file_protocol_v1_protocol_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protocol_v1_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_v1_protocol_proto_depIdxs,
		EnumInfos:         file_protocol_v1_protocol_proto_enumTypes,
		MessageInfos:      file_protocol_v1_protocol_proto_msgTypes,
	}.Build()
	File_protocol_v1_protocol_proto = out.File
	file_protocol_v1_protocol_proto_goTypes = nil
	file_protocol_v1_protocol_proto_depIdxs = nil
}
